app = 'game-server-starter'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[env]
  MIX_ENV = 'dev'
  PORT = '4000'
  SECRET_KEY_BASE = '1DdaMAX56nUh1tvXniEEuQNsGNvgADndawxrJ3YFZlLXc9EOahC/NFDgowCDUFwb'
  SQLITE_DATABASE_PATH = '/data/game_server_prod.db'

[[mounts]]
  source = 'game_server_data'
  destination = '/data'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'
